package main

import (
	"fmt"
	"log"
	"os"

	"hr-payroll/config"
	"hr-payroll/internal/delivery/handler"
	"hr-payroll/internal/delivery/http"
	"hr-payroll/internal/domain"
	"hr-payroll/internal/repository"
	"hr-payroll/internal/service"

	"github.com/gin-gonic/gin"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	// Swagger docs (generated by swag)
	_ "hr-payroll/docs"
)

// initDB menginisialisasi koneksi GORM ke PostgreSQL
func initDB() *gorm.DB {
	// Prefer an explicit full DSN if provided (DATABASE_URL or POSTGRES_DSN)
	if dsnEnv := os.Getenv("DATABASE_URL"); dsnEnv != "" {
		db, err := gorm.Open(postgres.Open(dsnEnv), &gorm.Config{})
		if err != nil {
			log.Fatalf("Failed to connect to database (DATABASE_URL): %v", err)
		}
		db.AutoMigrate(&domain.Employee{}, &domain.Attendance{}, &domain.Payroll{})
		return db
	}
	if dsnEnv := os.Getenv("POSTGRES_DSN"); dsnEnv != "" {
		db, err := gorm.Open(postgres.Open(dsnEnv), &gorm.Config{})
		if err != nil {
			log.Fatalf("Failed to connect to database (POSTGRES_DSN): %v", err)
		}
		db.AutoMigrate(&domain.Employee{}, &domain.Attendance{}, &domain.Payroll{})
		return db
	}

	// Otherwise load configuration from .env / environment via config package
	cfg := config.LoadConfig()

	dsn := fmt.Sprintf("host=%s user=%s password=%s dbname=%s port=%s sslmode=disable TimeZone=Asia/Jakarta",
		cfg.DBHost, cfg.DBUser, cfg.DBPassword, cfg.DBName, cfg.DBPort)

	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}

	// Auto-migrate skema tabel (Hanya untuk development!)
	db.AutoMigrate(&domain.Employee{}, &domain.Attendance{}, &domain.Payroll{})

	return db
}

// @title Mini HR & Payroll System API
// @version 1.0
// @description Backend Technical Test (Golang + PostgreSQL)
// @host localhost:8080
// @BasePath /api/v1
// @schemes http
func main() {
	// 1. INJEKSI DATABASE
	db := initDB()

	// 2. INJEKSI REPOSITORY (Implementasi Database Adapter)
	employeeRepo := repository.NewEmployeeGormRepository(db)
	attendanceRepo := repository.NewAttendanceGormRepository(db)
	payrollRepo := repository.NewPayrollGormRepository(db)

	// 3. INJEKSI SERVICE (Implementasi Use Case/Logika Bisnis)
	employeeService := service.NewEmployeeServiceImpl(employeeRepo)
	attendanceService := service.NewAttendanceServiceImpl(attendanceRepo)
	payrollService := service.NewPayrollServiceImpl(employeeRepo, attendanceRepo, payrollRepo)

	// 4. INJEKSI HANDLER (Delivery Adapter)
	employeeHandler := handler.NewEmployeeHandler(employeeService)
	attendanceHandler := handler.NewAttendanceHandler(attendanceService)
	payrollHandler := handler.NewPayrollHandler(payrollService)

	// 5. SETUP ROUTER (Memetakan Handler ke URL)
	router := gin.New()
	// Add Logger and Recovery middleware
	router.Use(gin.Logger())
	router.Use(gin.Recovery())

	routerConfig := http.RouterConfig{
		EmployeeHandler:   employeeHandler,
		AttendanceHandler: attendanceHandler,
		PayrollHandler:    payrollHandler,
	}
	http.SetupRouter(router, routerConfig)

	// 6. MENJALANKAN SERVER
	log.Println("Server running on port :8080. Swagger URL: http://localhost:8080/swagger/index.html")
	if err := router.Run(":8080"); err != nil {
		log.Fatalf("Server failed to run: %v", err)
	}
}
